name: Tests

on:
  workflow_dispatch:
  pull_request:

env:
  NODE_VERSION: "16.x"

jobs:
  playwright:
    runs-on: ubuntu-latest
    name: "Tests"
    defaults:
      run:
        working-directory: "tests/"
    steps:
      - name: Checkout project
        uses: actions/checkout@v4
      - name: Use Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: Install dependencies
        run: yarn
      - name: Install Playwright webkit
        run: npx playwright install webkit --with-deps
      - name: Run Playwright tests
        run: xvfb-run npx playwright test --project=webkit --headed
      - name: Generate HTML report
        if: always()
        run: |
          npx playwright merge-reports --reporter=html ./blob-report
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-html
          path: tests/playwright-report/
